In [20]:
import pandas as pd 
import numpy as np

In [21]:
#Load the DataSet 
df = pd.read_csv("./DSBDALExam/dataset_Facebook.csv" , sep=';')
df.head(5)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [22]:
#columns 
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [23]:
photo_posts = df[df['Type'] == 'Photo']
print("photo post Subset : \n")
print(photo_posts.head(1))

photo post Subset :

   Page total likes   Type  Category  Post Month  Post Weekday  Post Hour  \
0            139441  Photo         2          12             4          3

   Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0   0.0                       2752                             5091

   Lifetime Engaged Users  Lifetime Post Consumers  \
0                     178                      109

   Lifetime Post Consumptions  \
0                         159

   Lifetime Post Impressions by people who have liked your Page  \
0                                               3078

   Lifetime Post reach by people who like your Page  \
0                                              1640

   Lifetime People who have liked your Page and engaged with your post  \
0                                                119

   comment  like  share  Total Interactions
0        4  79.0   17.0                 100

In [24]:
status_post = df[df['Type'] == 'Status']
print( status_post.head())

    Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
1             139441  Status         2          12             3         10
5             139441  Status         2          12             1          9
8             139441  Status         2          12             7          3
10            139441  Status         2          12             5         10
15            138414  Status         2          12             3         10

    Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
1    0.0                      10460                            19057
5    0.0                      10472                            20849
8    0.0                      11844                            22538
10   0.0                      21744                            42334
15   0.0                      10060                            19680

    Lifetime Engaged Users  Lifetime Post Consumers  \
1                     1457                     1361
5                     1191                     1073
8                     1530                     1407
10                    4258                     4100
15                    1264                     1209

    Lifetime Post Consumptions  \
1                         1674
5                         1389
8                         1692
10                        4540
15                        1425

    Lifetime Post Impressions by people who have liked your Page  \
1                                               11710
5                                               16034
8                                               15220
10                                              37849
15                                              17272

    Lifetime Post reach by people who like your Page  \
1                                               6112
5                                               7852
8                                               7912
10                                             18952
15                                              8548

    Lifetime People who have liked your Page and engaged with your post  \
1                                                1108
5                                                1016
8                                                1250
10                                               3798
15                                               1162

    comment   like  share  Total Interactions
1         5  130.0   29.0                 164
5         1  152.0   33.0                 186
8         0  161.0   31.0                 192
10        0  233.0   19.0                 252
15        4   86.0   18.0                 108

In [28]:
# b)  Merge two subsets 
merged_data = pd.concat([status_post , photo_posts] ,ignore_index=True)
print("merged Subset : \n ")
print( merged_data.head())

merged Subset :

   Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0            139441  Status         2          12             3         10
1            139441  Status         2          12             1          9
2            139441  Status         2          12             7          3
3            139441  Status         2          12             5         10
4            138414  Status         2          12             3         10

   Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0   0.0                      10460                            19057
1   0.0                      10472                            20849
2   0.0                      11844                            22538
3   0.0                      21744                            42334
4   0.0                      10060                            19680

   Lifetime Engaged Users  Lifetime Post Consumers  \
0                    1457                     1361
1                    1191                     1073
2                    1530                     1407
3                    4258                     4100
4                    1264                     1209

   Lifetime Post Consumptions  \
0                        1674
1                        1389
2                        1692
3                        4540
4                        1425

   Lifetime Post Impressions by people who have liked your Page  \
0                                              11710
1                                              16034
2                                              15220
3                                              37849
4                                              17272

   Lifetime Post reach by people who like your Page  \
0                                              6112
1                                              7852
2                                              7912
3                                             18952
4                                              8548

   Lifetime People who have liked your Page and engaged with your post  \
0                                               1108
1                                               1016
2                                               1250
3                                               3798
4                                               1162

   comment   like  share  Total Interactions
0        5  130.0   29.0                 164
1        1  152.0   33.0                 186
2        0  161.0   31.0                 192
3        0  233.0   19.0                 252
4        4   86.0   18.0                 108

In [31]:
# c) Sort Data on Page total likes
sorted_data = df.sort_values(by="Page total likes" , ascending=True)
print("After Sorting :\n ")
print(sorted_data.head())

After Sorting :

     Page total likes   Type  Category  Post Month  Post Weekday  Post Hour  \
499             81370  Photo         2           1             4          4
496             81370  Photo         2           1             5          8
498             81370  Photo         3           1             4         11
497             81370  Photo         1           1             5          2
493             85093  Photo         3           1             1          2

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
499   NaN                       4188                             7292
496   0.0                       3480                             6229
498   0.0                       4156                             7564
497   0.0                       3778                             7216
493   0.0                       8412                            13960

     Lifetime Engaged Users  Lifetime Post Consumers  \
499                     564                      524
496                     537                      508
498                     626                      574
497                     625                      572
493                    1179                     1111

     Lifetime Post Consumptions  \
499                         743
496                         687
498                         832
497                         795
493                        1632

     Lifetime Post Impressions by people who have liked your Page  \
499                                               3861
496                                               3961
498                                               4534
497                                               4742
493                                               8632

     Lifetime Post reach by people who like your Page  \
499                                              2200
496                                              2104
498                                              2452
497                                              2388
493                                              5348

     Lifetime People who have liked your Page and engaged with your post  \
499                                                316
496                                                301
498                                                370
497                                                363
493                                                699

     comment   like  share  Total Interactions
499        0   91.0   28.0                 119
496        0   53.0   22.0                  75
498        7   91.0   38.0                 136
497        4   93.0   18.0                 115
493       17  185.0   55.0                 257

In [32]:
# d)  Transposing Data 
transpose_data = df.head().T
print("Transposed Data : \n ")
print(transpose_data.head())

Transposed Data :

                       0       1       2       3       4
Page total likes  139441  139441  139441  139441  139441
Type               Photo  Status   Photo   Photo   Photo
Category               2       2       3       2       2
Post Month            12      12      12      12      12
Post Weekday           4       3       3       2       2

In [33]:
# e) Melting Data to long format 
melted_data = pd.melt(
    df ,
    id_vars=['Type'],
    value_vars=['like' , 'share' , 'comment'],
    var_name='Metrics',
    value_name='Count'
)
melted_data.head()

     Type Metrics   Count
0   Photo    like    79.0
1  Status    like   130.0
2   Photo    like    66.0
3   Photo    like  1572.0
4   Photo    like   325.0

In [35]:
# f) Casting data to wide format (long to wide )
wide_data = melted_data.pivot_table(
    index='Type' ,
    columns='Metrics' ,
    values='Count' ,
    aggfunc='mean'
)
print("Long to Wide Data : \n")
print( wide_data.head())

Long to Wide Data :

Metrics    comment        like      share
Type
Link      2.818182   73.318182  12.909091
Photo     7.492958  182.611765  27.158768
Status    8.911111  176.711111  31.422222
Video    12.285714  231.428571  52.142857